/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SpiralTranscription.gltf --transform -R 8192 
Files: SpiralTranscription.gltf [1.21KB] > /Users/nate/Documents/local-repos/290A-CMPM-Poetics/what-was-said/generator/blender/SpiralTranscription-transformed.glb [16.05KB] (-1226%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SpiralTranscription-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SingleMesh.geometry} material={nodes.SingleMesh.material} />
    </group>
  )
}

useGLTF.preload('/SpiralTranscription-transformed.glb')
