/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SpiralTranscription.gltf --transform -R 8192 
Files: SpiralTranscription.gltf [3.21KB] > /Users/nate/Documents/local-repos/290A-CMPM-Poetics/what-was-said/generator/blender/SpiralTranscription-transformed.glb [258.53KB] (-7954%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SpiralTranscription-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SingleMesh.geometry} material={materials.BrightWhite} position={[0, -0.081, 0]} />
      <mesh geometry={nodes.Shield.geometry} material={materials.Shield} />
    </group>
  )
}

useGLTF.preload('/SpiralTranscription-transformed.glb')
